In [2]:
import numpy as np

a = np.array([10, 20, 30])

b = np.zeros(4)

c = np.ones((2, 3))

d = np.arange(0, 10, 2)

 

print(a)

print(b)

print(c)

print(d)

[10 20 30]
[0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]


In [3]:
import numpy as np

 

arr = np.array([[10, 20, 30],

                [40, 50, 60],

                [70, 80, 90]])

 

print(arr[0, 1])# row 0, col 1

print(arr[1][2]) # row 1, col 2

#print(arr [r][c])

print(arr[-1, -1]) # last row, last col

#print(arr[])

20
60
90


In [4]:
import numpy as np

a = np.array([10,12,14,17,18,23,45,15,78])

print(a[2:6])      # elements 2,3,4,5

print(a[:4])       # first four

print(a[::2])      # every second element

 

m = a.reshape(3,3)

print(m)

print(m[0:2, 1:3]) # first two rows, cols 1 and 2

[14 17 18 23]
[10 12 14 17]
[10 14 18 45 78]
[[10 12 14]
 [17 18 23]
 [45 15 78]]
[[12 14]
 [18 23]]


In [1]:
#combined practice set

#Filter high-value orders
#Problem: Given orders = [120, 760, 300, 1500, 99], print orders >= 500.
#Expected Output: [760, 1500]

orders = [120, 760, 300, 1500, 99]

result = []

for order in orders:
    if order >= 500:
        result.append(order)

print(result)


[760, 1500]


In [2]:
#Unique customer IDs

ids = [201, 202, 201, 203, 202]

unique_ids = set(ids)

print(unique_ids)

{201, 202, 203}


In [3]:
#Nested decision for shipping

is_express = True
weight = 8

if is_express:
    if weight <= 5:
        cost = 30
    else:
        cost = 50
else:
    if weight <= 5:
        cost = 10
    else:
        cost = 20

print(cost)

50


In [4]:
#Updating a dictionary

customer = {
    "id":301,
    "name":"Ravi"
}

customer["city"] = "Delhi"
customer["orders"] = []

print(customer)

{'id': 301, 'name': 'Ravi', 'city': 'Delhi', 'orders': []}


In [5]:
# Loop with continue
items = ['ok', '', None, 'good']

cleaned = []

for item in items:
    if not item:
        continue

    cleaned.append(item)

print(cleaned)

['ok', 'good']


In [6]:
# Ordered unique list
numbers = [5,3,5,2,3]

seen = set()
result = []

for num in numbers:
    if num not in seen:
        seen.add(num)
        result.append(num)

print(result)

[5, 3, 2]


In [17]:
#Mini Assignment (Customer Orders Processing)
customers = [
    {"id":401, "name":"Anita", "city":"Pune", "orders":[120,80]},
    {"id":402, "name":"Bhavesh", "city":"Mumbai", "orders":[1500]},
    {"id":403, "name":"Celine", "city":"Pune", "orders":[50,40,60]}
]

In [18]:
#1
high_value = []
cities = set()
total_sales = 0
follow_up = []

In [20]:
#2
for customer in customers:

    # unique cities
    cities.add(customer["city"])

    # calculate customer's total
    customer_total = sum(customer["orders"])

    # add to company sales
    total_sales += customer_total

    # high-value orders
    for order in customer["orders"]:
        if order >= 1000:
            high_value.append(customer["id"])

    # follow-up customers
    if customer_total < 200:
        follow_up.append(
            (customer["id"], customer["name"])
        )


print("High-value customers:", high_value)
print("Unique cities:", cities)
print("Total sales:", format(total_sales, ".2f"))
print("Follow-up customers:", follow_up)

High-value customers: [402]
Unique cities: {'Pune', 'Mumbai'}
Total sales: 1850.00
Follow-up customers: [(403, 'Celine')]


In [ ]:
#LAB | Python Control Flow and Data Structures Lab


In [24]:
#Lab 1: Pass / Fail using if

marks = 72

if marks >= 40:
    print("Pass")
else:
    print("Fail")

Pass


In [25]:
#Lab 2: Grade using if / elif / else
score = 83

if score >=90:
    print("Grade A")
elif score >= 75:
    print("Grade B")
elif score >= 60:
    print("Grade C")
elif score >= 40:
    print("Grade D")
else:
    print("Fail")

Grade B
